# Generated by Django 5.2.7 on 2025-10-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
            options={
                'db_table': 'employees',
                'indexes': [models.Index(fields=['gender', 'full_name'], name='employees_gender_b8d9d4_idx'), models.Index(fields=['full_name', 'birth_date'], name='employees_full_na_0e9f20_idx')],
            },
        ),
    ]
